name: Update target branch with changes from source branch

on:
  push:
    branches:
      - source_branch

jobs:
  update_target_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: target_branch
      - name: Merge changes from source branch into target branch
        run: |
          git merge --no-commit --no-ff origin/source_branch
          git commit -m "Merge changes from source branch into target branch"
          git push origin target_branch
