name: Update C on Push to A or B

on:
  push:
    branches:
      - a
      - b

jobs:
  update-c:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Merge A and B into C
      run: |
        git checkout c
        git merge --no-commit a
        git merge --no-commit b
        git commit -m "Merge A and B into C"
        git push
