name: Update target branch with changes from source branch

on:
  push:
    branches:
      - a
      - b

jobs:
  update_c:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set Job-specific Git Account
        run: |
          git config user.email "you@example.com"
          git config user.name "Your Name"
      - name: Fetch and Checkout Target Branch
        run: |
          git remote add upstream https://github.com/tsusk8/auto_pull.git
          git fetch upstream
          git checkout c
          git pull --no-commit upstream c
      - name: Merge Branch into Target Branch
        run: |
          git merge --allow-unrelated-histories --no-commit --no-ff ${{ github.ref }}
          if [ $? -ne 0 ]; then
            git status --porcelain | grep '^U ' | sed -e 's/^U //g' | xargs -n1 git checkout --theirs
            git add .
          fi
          git commit -m "Automatic merge"
          git push upstream c
