name: Update C on Push to A or B

on:
  push:
    branches:
      - a
      - b

jobs:
  update-c:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Merge A and B into C
      run: |
        git remote add upstream https://github.com/tsusk8/auto_pull.git
        git fetch upstream
        git checkout a
        git pull --no-commit upstream a
        git checkout b
        git pull --no-commit upstream b
        git checkout c
        git pull --no-commit upstream c
        git merge --allow-unrelated-histories --no-commit a
        git merge --allow-unrelated-histories --no-commit b
        git commit -m "Merge A and B into C"
        git push --allow-unrelated-histories
